Rename folders
fpga-open-speech-tools/component_library pull request #10
Opened 2020-07-23 22:26 UTC by flatearth-vannoy

Folders are now snake_case, and the Source_Files folders are gone.
Updated gitignore to ignore generated files

If there are any Quartus projects that explicitly have any of these directories in their library search path, those projects are likely now broken and need to be updated.

2020-07-23 23:14 UTC, fe-wickham requested changes
Mostly looks good. Some .mod files did get added in, probably before the .gitignore. Additionally, should the AD1939 pdf docs be deleted?

2020-07-23 23:14 UTC, fe-wickham commented on ad1939/.tmp_versions/FE_AD1939.mod
> +/mnt/data/NIH/component_library/AD1939/Source_Files/FE_AD1939.ko
Remove file

2020-07-23 23:14 UTC, fe-wickham commented on qsys_simple_ha/.tmp_versions/FE_Qsys_Simple_HAv8.mod
> +/mnt/data/NIH/component_library/Qsys_Simple_HAv8/Source_Files/FE_Qsys_Simple_HAv8.ko
Remove file

2020-07-23 23:46 UTC, tvannoy commented
> should the AD1939 pdf docs be deleted?

I don't think there's much reason to have external datasheets in our version control. I think we should include links to them in our READMEs, though.

2020-07-27 14:11 UTC, rksnider commented
Links would be fine.


On Thu, Jul 23, 2020 at 5:46 PM Trevor Vannoy <notifications@github.com>
wrote:

> should the AD1939 pdf docs be deleted?
>
> I don't think there's much reason to have external datasheets in our
> version control. I think we should include links to them in our READMEs,
> though.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fpga-open-speech-tools/component_library/pull/10#issuecomment-663285843>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNDUXEDNBN5I5ISYNAXXZ3R5DDVNANCNFSM4PGFMVZQ>
> .
>

2020-07-27 19:11 UTC, fe-wickham approved these changes
Looks good

2020-07-27 19:11 UTC, merged